# Simple Sentiment Analysis Sub-Pipeline
id: sentiment_analysis
name: Sentiment Analysis Sub-Pipeline
description: Analyze sentiment in text data
version: "2.0.0"

parameters:
  data:
    type: object
    description: Input data with text to analyze
  text_column:
    type: string
    default: "comments"

steps:
  - id: analyze_sentiment
    tool: task-delegation
    action: batch_process
    parameters:
      tasks: |
        Analyze the sentiment of the following text samples and rate each on a scale of 1-5 
        (1=very negative, 5=very positive):
        
        Data: {{ inputs.data | default('Sample text for analysis') }}
        
        Return a JSON object with sentiment scores for each item.
      model: <AUTO>
      batch_size: 10
      parallel: true
    
  - id: summarize_sentiment
    action: generate_text
    parameters:
      prompt: |
        Based on the sentiment analysis results:
        {{ analyze_sentiment.result | default('No sentiment data') }}
        
        Provide a brief summary of overall sentiment trends.
      model: <AUTO>
    dependencies:
      - analyze_sentiment

outputs:
  sentiment_scores: "{{ analyze_sentiment.result }}"
  sentiment_summary: "{{ summarize_sentiment.result }}"