# Main configuration for the Orchestrator Framework

orchestrator:
  # Basic settings
  name: orchestrator
  version: 1.0.0
  
  # Execution settings
  execution:
    max_concurrent_tasks: 10
    default_timeout: 300  # 5 minutes
    max_retries: 3
    checkpoint_enabled: true
    
  # Resource management
  resources:
    cpu_cores: 8
    memory_gb: 16
    gpu_memory_gb: 8
    disk_space_gb: 100
    
    # Resource allocation strategies
    allocation_strategy: fair_share  # fair_share, priority, first_come_first_served
    
    # Resource limits per task
    task_limits:
      cpu_cores: 4
      memory_gb: 8
      gpu_memory_gb: 4
      timeout: 600  # 10 minutes
  
  # Error handling
  error_handling:
    circuit_breaker:
      failure_threshold: 5
      recovery_timeout: 30
      half_open_max_calls: 3
      
    retry_strategy:
      max_attempts: 3
      base_delay: 1.0
      max_delay: 60.0
      exponential_base: 2.0
      jitter: true
      
    failure_policies:
      default: fail  # fail, continue, skip, retry
      per_task: {}  # Override per task ID
  
  # Caching
  cache:
    enabled: true
    memory_cache:
      max_size: 1000
      ttl: 3600  # 1 hour
      
    disk_cache:
      enabled: true
      directory: "./cache"
      max_size_gb: 5
      ttl: 86400  # 24 hours
      
    distributed_cache:
      enabled: false
      redis_url: "redis://localhost:6379"
  
  # State management
  state:
    backend: file  # file, redis, postgres
    directory: "./checkpoints"
    
    # Checkpoint strategy
    checkpoint:
      strategy: adaptive  # time_based, progress_based, adaptive
      interval: 60  # seconds
      progress_threshold: 0.25  # 25% progress
      
  # Logging
  logging:
    level: INFO
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "./logs/orchestrator.log"
    max_bytes: 10485760  # 10MB
    backup_count: 5
    
  # Monitoring
  monitoring:
    enabled: true
    metrics_port: 8080
    health_check_interval: 30
    
    # Performance tracking
    track_performance: true
    track_costs: true
    track_resources: true
    
  # Security
  security:
    sandbox_enabled: true
    allow_network: false
    allow_file_system: true
    max_execution_time: 3600  # 1 hour
    
    # API rate limiting
    rate_limiting:
      enabled: true
      requests_per_minute: 60
      burst_size: 10
      
# Development settings
development:
  debug: false
  mock_models: false
  disable_sandboxing: false
  log_level: DEBUG
  
# Production settings
production:
  debug: false
  mock_models: false
  disable_sandboxing: false
  log_level: INFO
  
  # Production-specific overrides
  execution:
    max_concurrent_tasks: 50
    checkpoint_enabled: true
    
  monitoring:
    enabled: true
    health_check_interval: 10
    
  security:
    sandbox_enabled: true
    allow_network: false