#!/usr/bin/env python3
"""Generate docs/actions.md from the action registry.

The vocabulary is documented from the same object the executor dispatches on,
so the documentation cannot describe an action that does not exist or miss one
that does. `tests/test_action_contract_docs.py` re-runs this and fails if the
committed file differs, which is what stops the two drifting apart.

    python scripts/generate_action_docs.py           # write docs/actions.md
    python scripts/generate_action_docs.py --check   # exit 1 if out of date
"""

from __future__ import annotations

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from orchestrator.core.actions import ACTION_FAMILIES, ACTION_SPECS  # noqa: E402
from orchestrator.core.routing import FAILURE_POLICIES  # noqa: E402

TARGET = ROOT / "docs" / "actions.md"

HEADER = """<!-- Generated by scripts/generate_action_docs.py. Do not edit by hand. -->

# Action vocabulary

A step names **either** a tool and an operation on it:

```yaml
- id: save
  tool: filesystem
  action: write
  parameters:
    path: out/report.md
    content: "..."
```

**or** an action the runtime executes itself:

```yaml
- id: think
  action: generate
  parameters:
    prompt: "Summarise the findings"
```

This page lists the second group. It is generated from
`orchestrator.core.actions`, the single registry the executor dispatches on and
the validator recognises, so it cannot fall out of step with the code.

An action that appears nowhere on this page is **refused**. It is not turned
into a prompt for the model: `action: gernate` is a typo and fails, at compile
time and again at dispatch.

## When does a pipeline fail, and with which exit code?

| Situation | Detected | Exit code |
|-|-|-|
| Malformed YAML, unknown action, missing required parameter, dependency on a step that does not exist, template that can never resolve | compile time (`orchestrator validate`) | **2** |
| A reference expected to resolve from an earlier step's result, still unresolved at the moment a tool would use it | run time, before any side effect | **1** |
| A step raising during execution | run time | **1** |

The distinction matters because template resolution runs in several passes. A
reference to a prior step cannot be resolved before that step has run, so it is
not a compile error -- but it must not survive to the point where a value is
written to a file or sent to a model. At that boundary it fails the step, no
output is written, and the run exits 1.

"""


def render() -> str:
    lines = [HEADER, "## Actions\n"]
    lines.append("| Action | Requires | Required parameters | Aliases | Description |")
    lines.append("|-|-|-|-|-|")
    for spec in sorted(ACTION_SPECS, key=lambda s: s.name):
        aliases = ", ".join(f"`{a}`" for a in sorted(spec.aliases)) or "—"
        required = ", ".join(f"`{p}`" for p in sorted(spec.required_parameters)) or "—"
        requires = "—" if spec.requires == "none" else spec.requires
        lines.append(
            f"| `{spec.name}` | {requires} | {required} | {aliases} | {spec.summary} |"
        )

    lines.append("")
    lines.append("Aliases are accepted but deprecated: the compiler rewrites them to the")
    lines.append("canonical name, emits a `DeprecationWarning`, and only the canonical")
    lines.append("spelling appears in the task graph and the execution trace.")
    lines.append("")

    lines.append("## Prose families\n")
    lines.append(
        "Two shapes are matched by pattern rather than by name, because they are\n"
        "written as instructions rather than identifiers.\n"
    )
    lines.append("| Family | Description |")
    lines.append("|-|-|")
    for family in sorted(ACTION_FAMILIES, key=lambda f: f.name):
        lines.append(f"| `{family.name}` | {family.summary} |")
    lines.append("")
    lines.append(
        "`<AUTO>...</AUTO>` is the one case where an instruction is deliberately\n"
        "handed to the model to interpret. That is an explicit request, which is why\n"
        "it remains supported while the implicit \"unrecognised action becomes a\n"
        "prompt\" behaviour does not.\n"
    )

    lines.append("## Control-flow routing\n")
    lines.append(
        "A step may name where execution goes next. Routing jumps **forward**;\n"
        "steps between the source and the target are marked `skipped`. Skipping is\n"
        "not failing -- a pipeline that routed around a step still succeeds.\n"
    )
    lines.append("| Key | Fires when |")
    lines.append("|-|-|")
    lines.append(
        "| `on_false` | the step's own `condition:` was false, so it was skipped |"
    )
    lines.append("| `on_success` | the step ran and succeeded |")
    lines.append("| `on_failure` | the step ran and did not succeed |")
    lines.append("")
    policies = ", ".join(f"`{p}`" for p in sorted(FAILURE_POLICIES))
    lines.append(
        f"`on_failure` means two things, told apart by value. These are failure\n"
        f"**policies**: {policies}. Any other value names a **step to jump to**,\n"
        f"and the run continues there instead of aborting.\n"
    )
    lines.append(
        "A step whose id is one of those policy words is refused at compile time,\n"
        "since routing to it could not be distinguished from selecting the policy.\n"
        "Routing targets are checked at compile time too: a jump to a step that\n"
        "does not exist, or a step routing to itself, is exit 2.\n"
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify, do not write")
    args = parser.parse_args()

    rendered = render()
    if args.check:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != rendered:
            print(f"{TARGET.relative_to(ROOT)} is out of date.", file=sys.stderr)
            print("Regenerate with: python scripts/generate_action_docs.py", file=sys.stderr)
            return 1
        print(f"{TARGET.relative_to(ROOT)} is up to date.")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered)
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
