#!/usr/bin/env python3
"""Generate docs/template_globals.md from the pipeline-global registry.

The page is written from the same specs the validator checks calls against, so
it cannot document a global that does not exist, miss one that does, or state
an argument count the validator would reject.
`tests/test_template_globals.py` re-runs this and fails if the committed file
differs.

    python scripts/generate_template_globals_docs.py           # write the page
    python scripts/generate_template_globals_docs.py --check   # exit 1 if stale
"""

from __future__ import annotations

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from orchestrator.core.template_globals import GLOBAL_SPECS  # noqa: E402

TARGET = ROOT / "docs" / "template_globals.md"

HEADER = """<!-- Generated by scripts/generate_template_globals_docs.py. Do not edit by hand. -->

# Template globals

A pipeline template can call these functions:

```yaml
- id: save
  tool: filesystem
  action: write
  parameters:
    path: "report-{{ execution.timestamp }}.md"
    content: "{{ include_file('header.md') }}"
```

They are **not** filters. A filter transforms a value the author already holds,
so any Jinja environment can evaluate one. Each global below answers a question
about the state of a *run*, so only the runtime can evaluate it:

```yaml
- id: make_it     # writes ./artifact
- id: check_it    # content: "{{ file_exists('artifact') }}"  ->  True
```

`check_it` renders `True` because by then `make_it` has run. The compiler and
the validators therefore know these names but hold none of the implementations
-- if they held them, that expression would be answered at compile time, before
any step had run, and would write `False` into the file with nothing failing.

## Calling them

A global must be **called**. Naming one without calling it renders the function
object itself:

| Written | Result |
|-|-|
| `{{ now() }}` | the time |
| `{{ now }}` | `<function ...now at 0x1084...>` written into your artifact |
| `{{ now.foo }}` | fails at run time |
| `{{ now(1, 2) }}` | fails at run time |

All three of the wrong forms are refused at compile time (`orchestrator
validate`, exit 2).

"""


def render() -> str:
    lines = [HEADER, "## Available globals\n"]
    lines.append("| Global | Arguments | Description |")
    lines.append("|-|-|-|")
    for spec in sorted(GLOBAL_SPECS, key=lambda s: s.name):
        lines.append(f"| `{spec.name}` | {spec.arity} | {spec.summary} |")
    lines.append("")
    lines.append(
        "A name that is not on this list is not a global. `{{ nowx() }}` is a\n"
        "typo and is refused at compile time rather than becoming an undefined\n"
        "value at run time.\n"
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify, do not write")
    args = parser.parse_args()

    rendered = render()
    if args.check:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != rendered:
            print(f"{TARGET.relative_to(ROOT)} is out of date.", file=sys.stderr)
            print(
                "Regenerate with: python scripts/generate_template_globals_docs.py",
                file=sys.stderr,
            )
            return 1
        print(f"{TARGET.relative_to(ROOT)} is up to date.")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered)
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
