#!/usr/bin/env python3
"""Debug template rendering issue."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from orchestrator.compiler.template_renderer import TemplateRenderer

# Test template
template = """# Research Summary: {{topic}}

**Date:** {{ execution.timestamp }}
**Sources Reviewed:** {{search_web.total_results}}

## Summary

{{summarize_results.result}}

## Sources

{% for result in search_web.results %}
{{loop.index}}. [{{result.title}}]({{result.url}})
   > {{result.snippet}}
{% endfor %}

---
*Generated by Simple Research Pipeline*"""

# Test context
context = {
    "topic": "artificial intelligence",
    "execution": {
        "timestamp": "2025-07-29 07:30:00"
    },
    "search_web": {
        "total_results": 5,
        "results": [
            {
                "title": "AI Article 1",
                "url": "https://example.com/1",
                "snippet": "AI is transforming the world"
            },
            {
                "title": "AI Article 2", 
                "url": "https://example.com/2",
                "snippet": "Machine learning advances"
            }
        ]
    },
    "summarize_results": {
        "result": "AI is rapidly advancing in multiple fields."
    }
}

# Render template
rendered = TemplateRenderer.render(template, context)
print("Rendered output:")
print(rendered)